### PR TITLE
Release 0.2.1

### PR DESCRIPTION
**Pull request by densh**
/cc @sjrd

### CODE REVIEW

**Comment by densh** [comment]
It looks like travis is overloaded right now.

**Comment by sjrd** [comment]
The actual Travis job is green: https://travis-ci.org/scala-native/sbt-crossproject/builds/262325814?utm_source=github_status&utm_medium=notification
It just failed to update the status on GitHub.

**Comment by densh** [comment]
@sjrd sbt-crossproject is published now for both 0.13 and 1.0.0-RC3. ` sbt-scalajs-crossproject` is only available for 0.13, as `sbt-scalajs` is not yet available for 1.0.0-RC3.

**Comment by sjrd** [comment]
Excellent, thank you!

`sbt-scalajs` 0.6.19 is supposed to be available for any sbt >= 1.0.0-RC2. The sbt team decided that RCs would be binary compatible with each other and with 1.x final, so having published it for 1.0.0-RC2, it should be available for 1.0.0-RC3 as well.

**Comment by densh** [comment]
@sjrd 
```
# sbt
[info] Loading project definition from /Users/denys/.src/sbt-crossproject/project
[info] Set current project to sbt-crossproject-root (in build file:/Users/denys/.src/sbt-crossproject/)
> ++ 2.12.3
[info] Setting version to 2.12.3
[info] Reapplying settings...
[info] Set current project to sbt-crossproject-root (in build file:/Users/denys/.src/sbt-crossproject/)
> ^^ 1.0.0-RC3
[info] Setting `sbtVersion in pluginCrossBuild` to 1.0.0-RC3
[info] Set current project to sbt-crossproject-root (in build file:/Users/denys/.src/sbt-crossproject/)
> compile
[info] Updating {file:/Users/denys/.src/sbt-crossproject/}sbt-crossproject-test...
[info] Resolving org.scala-sbt#launcher;1.0.0 ...
[info] Done updating.
[info] Updating {file:/Users/denys/.src/sbt-crossproject/}sbt-scalajs-crossproject...
[info] Resolving org.scala-js#sbt-scalajs;0.6.19 ...
[warn]  module not found: org.scala-js#sbt-scalajs;0.6.19
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-js/sbt-scalajs/scala_2.12/sbt_0.13/0.6.19/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-js/sbt-scalajs/scala_2.12/sbt_0.13/0.6.19/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/denys/.ivy2/local/org.scala-js/sbt-scalajs/scala_2.12/sbt_0.13/0.6.19/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-js/sbt-scalajs_2.12_0.13/0.6.19/sbt-scalajs-0.6.19.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/denys/.sbt/preloaded/org.scala-js/sbt-scalajs/0.6.19/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/denys/.sbt/preloaded/org/scala-js/sbt-scalajs_2.12_0.13/0.6.19/sbt-scalajs-0.6.19.pom
[warn] ==== bintray-scala-native-sbt-plugins: tried
[warn]   https://dl.bintray.com/scala-native/sbt-plugins/org/scala-js/sbt-scalajs_2.12_0.13/0.6.19/sbt-scalajs-0.6.19.pom
[info] Resolving org.scala-sbt#launcher;1.0.0 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-js#sbt-scalajs;0.6.19: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.scala-js:sbt-scalajs:0.6.19 (scalaVersion=2.12, sbtVersion=0.13)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.scala-js:sbt-scalajs:0.6.19 (scalaVersion=2.12, sbtVersion=0.13) ((sbt.BuildExtra) Defaults.scala#L2070)
[warn]            +- org.scala-native:sbt-scalajs-crossproject:0.2.1 (scalaVersion=2.12, sbtVersion=1.0)
[trace] Stack trace suppressed: run last sbt-scalajs-crossproject/*:update for the full output.
[error] (sbt-scalajs-crossproject/*:update) sbt.ResolveException: unresolved dependency: org.scala-js#sbt-scalajs;0.6.19: not found
[error] Total time: 4 s, completed Aug 9, 2017 12:30:11 PM
```

**Comment by densh** [comment]
It's extremely surprising that it's looking for (2.12, 0.13) and (2.12, 1.0).

**Comment by sjrd** [comment]
Hum yes that's not normal. Obviously (2.12, 0.13) does not exist. It should be looking for (2.12, 1.0).
@dwijnand Are we missing something here? In this case we have an sbt plugin that we cross-compile, that is supposed to depend on another cross-built sbt plugin. Maybe this is not a common enough case, and `^^` has a bug in that situation?

**Comment by sjrd** [comment]
I have the same issue in the CI for https://github.com/scala-js/scala-js/pull/3093, se log at https://scala-webapps.epfl.ch/jenkins/job/scalajs-task-worker/188566/console.

Definitely looks like a bug in `^^`.

**Comment by dwijnand** [comment]
The situation with set/++/^^ is precarious to say the least. There's a few issues opened about it already, have a look and open more if you think your case isn't covered.

**Comment by sjrd** [comment]
Ah indeed, it's most certainly https://github.com/sbt/sbt/issues/3393.

**Pull request merged**
